### ISSUE TITLE
Broken compatibility with nanoPhotosProvider

### ISSUE THREAD

**Issue by Shultc** [Kris-B/nanoGALLERY#87]
nanoPhotosProvider works fine with nanoGALLERY v5.3.0beta, However, when used last version of nanoGALLERY (v5.7.0) in every album and in the root shows only one picture.

**Comment by eae710** [comment]
Hi, yeap, new version 5.8.0 have the same behavior (in every album and in the root shows only one picture).
Please fix!

**Comment by Kris-B** [comment]
Please have a look at v0.9.0: https://github.com/Kris-B/nanoPhotosProvider/releases/tag/v0.9.0
Incompatibility with latest nanoGALLERY versions has been fixed, but please use nanoGALLERY v5.9.0beta1 which is located in the demonstration folder of nanoPhotosProvider (do not use v5.8.0).

**Comment by eae710** [comment]
Excellent!! works veery well!! thanks a lot!

**Comment by Kris-B** [comment]
;-)

thx for the update

**Comment by eae710** [comment]
Hi!

my little contribution.

i18n spanish, for nanoGALLERY.
How use?, simply add the file *jquery.nanogallery-es.js* and set var
*nanoGallery_es
*to i18n:
Attachment a sample of use.

[image: Imágenes integradas 1]

Another little  contribution, the sort in nanoPhotosProvider.JSON.class.php
not work fine, because there is not difference between album and photo, so
I added some lines to fix it.

[image: Imágenes integradas 2]

Thanks a lot!

Regards from Mexico ;)



2015-10-16 2:42 GMT-05:00 Christophe Brisbois <notifications@github.com>:

> ;-)
>
> thx for the update
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Kris-B/nanoGALLERY/issues/87#issuecomment-148639441>.
>



-- 
Emmanuel

**Comment by Kris-B** [comment]
Hi @eae710 !

thanks for the contribution but it seems that the attachments got lost...

**Comment by eae710** [comment]
Hi @Kris-B , I send you a email in your domain brisbois.fr. I hope your comments, regards.

**Comment by Kris-B** [comment]
Yes Emmanuel, I got it.
I will include your contribution in the next release.
Many thanks!

**Comment by eae710** [comment]
Wow thank you very much!
